POST http://localhost:3000/sessions/signup
Content-Type: application/json

{
  "nombre": "Tester 2",
  "correo": "test.test2@gmail.com",
  "password": "password"
}

POST http://localhost:3000/sessions/login
Content-Type: application/json

{
  "correo": "test.test@gmail.com",
  "password": "password"
}

POST http://localhost:3000/sessions/logout
Content-Type: application/json

{
  "correo": "test.test@gmail.com"
}

POST http://localhost:3000/sessions/change_pass
Content-Type: application/json

{
  "correo": "test.test@gmail.com",
  "newPassword": "newPassword"
}