GET http://localhost:3000/users
GET http://localhost:3000/users?role=admin
GET http://localhost:3000/users?state=true
GET http://localhost:3000/users/1
POST http://localhost:3000/users/update
Content-Type: application/json

{
  "firstName": "Thiago",
  "lastName": "Checa",
  "email": "thiago.checa@gmail.com"
}